
   
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: php-crud-web
    volumes:
      - ./src:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    # container_name: php-crud-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
